export const questions = [
    {nepal : "In which country is Mount Everest?"},
    {marathon : "What is the longest running race in the Olympic Games?"},
    {madrid : "What is the capital of Spain?"},
    {tennis : "Which sport is played at Wimbledon?"},
    {smith : "What is the most common surname in the United States?"},
    {Yellow : "Aureolin is a shade of what color?"},
    {Delta : "What is the 4th letter of the Greek alphabet?"},
    {Rome : "What city is known as 'The Eternal City'?"},
    {Saturn : "Which planet has the most moons?"},
    {Tanzania : "In what country would you find Mount Kilimanjaro?"},
    {Brazil : "What country has won the most World Cups?"},
    {Mexico : "What is the largest Spanish-speaking city in the world?"},
    {Mercury : "What planet is closest to the sun?"},
    {Jaw : "Where is the strongest human muscle located?"},
    {london : "What is the capital of England?"},
    {paris : "What is the capital of France?"},
    {Albany : "What is the state capital of New York?"},
    {Dublin : "What is the capital of Ireland?"},
    {Redwoods : "What is the tallest type of tree?"},
    {Ottawa : "What is the capital of Canada?"},
    {Bristol : "Street artist Banksy is originally associated with which British city?"},
    {Maggot : "What is the common name for the larva of a housefly?"},
    {Krone : "What is the currency of Denmark?"},
    {Football : "What sport did David Beckham play?"},
    {Pasta : "What kind of food is Penne?"},
    {Red : "Which colour pill does Neo swallow in The Matrix?"},
    {Woody : "What’s the name of the cowboy in Toy Story?"},
    {Android : "Which operating system does a Google Pixel phone use?"},
    {Goose : "What Top Gun character is Captain Marvel's cat named after?"},
    {Green : "What colour are the seats in the House of Commons?"},
    {Denmark : "In which country would you find the original Legoland?"},
    {Ghost : "What is the name of Jon Snow's direwolf?"},
    {Lily : "What is the name of Harry's mother?"},
    {Nagini : "What is the name of Voldermort's pet snake?"},
    {Badger : "What animal represents Hufflepuff house?"},
    {Iran : "In which country would a thumbs up be considered a rude gesture?"},
    {Kiwi : "What flightless bird is the native symbol of New Zealand?"},
    {Rice : "From what grain is the Japanese spirit Sake made?"},
    {Ewoks : "Which species believed that C-3PO might be 'some sort of god'?"},
    {Gungan : "Jar Jar Binks belongs to what species?"},
]